server.port : 4000
spring:
  security:
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb2
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never